// src/react/SeamlessScroll.tsx
import React, { useRef, useEffect, useImperativeHandle, forwardRef } from 'react';
import type { ForwardedRef, ReactNode } from 'react';
import type { SeamlessScrollOptions } from '../../types';
import { SeamlessScroll } from '../../core';

export interface SeamlessScrollProps extends SeamlessScrollOptions {
  children?: ReactNode;
  running?: boolean;
}

export interface SeamlessScrollRef {
  start: () => void;
  stop: () => void;
  destroy: () => void;
  updateData: (data: string[]) => void;
  setOptions: (options: Partial<SeamlessScrollOptions>) => void;
  isRunning: () => boolean | undefined;
}

const SeamlessScrollComponent = (
  props: SeamlessScrollProps,
  ref: ForwardedRef<SeamlessScrollRef>
) => {
  const rootRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<SeamlessScroll | null>(null);

  useImperativeHandle(ref, () => ({
    start: () => instanceRef.current?.start(),
    stop: () => instanceRef.current?.stop(),
    destroy: () => instanceRef.current?.destroy(),
    updateData: (data) => instanceRef.current?.updateData(data),
    setOptions: (options) => instanceRef.current?.setOptions(options),
    isRunning: () => instanceRef.current?.isRunning(),
  }), []);

  useEffect(() => {
    if (rootRef.current) {
      instanceRef.current = new SeamlessScroll(rootRef.current, props);
      if (props.running === false) {
        instanceRef.current.stop();
      }
    }
    return () => {
      instanceRef.current?.destroy();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (instanceRef.current && props.running !== undefined) {
      if (props.running) instanceRef.current.start();
      else instanceRef.current.stop();
    }
  }, [props.running]);

  useEffect(() => {
    if (instanceRef.current && props.data) {
      instanceRef.current.updateData(props.data);
    }
  }, [props.data]);

  return (
    <div ref={rootRef} style={{ width: '100%', height: '100%', overflow: 'hidden', position: 'relative' }}>
      {props.children}
    </div>
  );
};

export const SeamlessScroll = forwardRef(SeamlessScrollComponent);
export default SeamlessScroll;

// src/vue/SeamlessScroll.vue
<template>
  <div ref="rootRef" class="seamless-scroll-vue">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, defineProps, defineExpose } from 'vue';
import type { SeamlessScrollOptions } from '../../types';
import { SeamlessScroll } from '../../core';

const props = defineProps<SeamlessScrollOptions & {
  modelValue?: boolean
}>();

const rootRef = ref<HTMLElement | null>(null);
let instance: SeamlessScroll | null = null;

const start = () => instance?.start();
const stop = () => instance?.stop();
const destroy = () => instance?.destroy();
const updateData = (data: string[]) => instance?.updateData(data);
const setOptions = (options: Partial<SeamlessScrollOptions>) => instance?.setOptions(options);
const isRunning = () => instance?.isRunning();

defineExpose({ start, stop, destroy, updateData, setOptions, isRunning });

onMounted(() => {
  if (rootRef.value) {
    instance = new SeamlessScroll(rootRef.value, props);
    if (props.modelValue === false) {
      instance.stop();
    }
  }
});

onBeforeUnmount(() => {
  destroy();
});

watch(() => props.modelValue, (val) => {
  if (!instance) return;
  if (val) instance.start();
  else instance.stop();
});

watch(() => props.data, (val) => {
  if (instance) instance.updateData(val);
});
</script>

<style scoped>
.seamless-scroll-vue {
  width: 100%;
  height: 100%;
  overflow: hidden;
  position: relative;
}
</style>
