// src/vue/ScrollSeamless.vue
<template>
  <div ref="rootRef" class="scroll-seamless-vue" :class="customClass" :style="customStyle">
    <template v-if="props && (props.direction === 'left' || props.direction === 'right')">
      <div v-for="(row, rowIdx) in renderMatrix" :key="rowIdx" class="scroll-seamless-row" :style="rowStyle(rowIdx)">
        <div class="ss-content ss-content-1" :class="props && props.contentClass" :style="{ ...ssContentStyle, transform: transforms[rowIdx*2] }">
          <slot
            v-for="(item, idx) in row"
            :key="idx"
            :item="item"
            :index="idx"
            :rowIndex="rowIdx"
          >
            <span class="ss-item" :class="props && props.itemClass" :style="itemStyle">{{ item }}</span>
          </slot>
        </div>
        <div class="ss-content ss-content-2" :class="props && props.contentClass" :style="{ ...ssContentStyle, transform: transforms[rowIdx*2+1] }">
          <slot
            v-for="(item, idx) in row"
            :key="`dup-${idx}`"
            :item="item"
            :index="idx"
            :rowIndex="rowIdx"
          >
            <span class="ss-item" :class="props && props.itemClass" :style="itemStyle">{{ item }}</span>
          </slot>
        </div>
      </div>
    </template>
    <template v-else>
      <div v-for="(col, colIdx) in renderMatrix" :key="colIdx" class="scroll-seamless-col" :style="colStyle(colIdx)">
        <div class="ss-content ss-content-1" :class="props && props.contentClass" :style="{ ...ssContentStyle, transform: transforms[colIdx*2] }">
          <slot
            v-for="(item, idx) in col"
            :key="idx"
            :item="item"
            :index="idx"
            :colIndex="colIdx"
          >
            <span class="ss-item" :class="props && props.itemClass" :style="itemStyle">{{ item }}</span>
          </slot>
        </div>
        <div class="ss-content ss-content-2" :class="props && props.contentClass" :style="{ ...ssContentStyle, transform: transforms[colIdx*2+1] }">
          <slot
            v-for="(item, idx) in col"
            :key="`dup-${idx}`"
            :item="item"
            :index="idx"
            :colIndex="colIdx"
          >
            <span class="ss-item" :class="props && props.itemClass" :style="itemStyle">{{ item }}</span>
          </slot>
        </div>
      </div>
    </template>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, watch, onMounted, onBeforeUnmount, computed, nextTick, PropType, StyleValue } from 'vue';
import { ScrollSeamless } from '../core';
import { getRenderData } from '../core/utils';
import { ScrollDirection, ScrollSeamlessOptions, ScrollSeamlessController } from '../types';

export default defineComponent({
  name: 'ScrollSeamlessVue',
  props: {
    data: { type: Array as PropType<string[]>, default: () => [] },
    direction: { type: String as PropType<ScrollDirection>, default: 'left' },
    minCountToScroll: { type: Number, default: 2 },
    step: { type: Number, default: 1 },
    stepWait: { type: Number, default: 0 },
    delay: { type: Number, default: 0 },
    bezier: { 
      type: Array as PropType<number[]>, 
      default: () => [0.25, 0.1, 0.25, 1] 
    },
    hoverStop: { type: Boolean, default: true },
    wheelEnable: { type: Boolean, default: false },
    singleLine: { type: Boolean, default: false },
    class: { type: [String, Object, Array] as PropType<StyleValue>, default: '' },
    style: { type: [String, Object, Array] as PropType<StyleValue>, default: '' },
    contentClass: { type: [String, Object, Array] as PropType<StyleValue>, default: '' },
    itemClass: { type: [String, Object, Array] as PropType<StyleValue>, default: '' },
    rows: { type: Number, default: 1 },
    cols: { type: Number, default: 1 },
    modelValue: { type: Boolean, default: undefined }
  },
  emits: [],
  setup(props, { expose }) {
    const rootRef = ref<HTMLElement | null>(null);
    let instance: ScrollSeamlessController | null = null;
    let resizeObserver: ResizeObserver | null = null;

    // 检测 JSDOM 测试环境
    const isJSDOM = typeof window !== 'undefined' && window.navigator && window.navigator.userAgent && window.navigator.userAgent.includes('jsdom');

    // 渲染矩阵：测试环境下直接用原始 data
    const renderMatrix = ref<string[][]>(isJSDOM ? [props.data] : []);
    const transforms = ref<string[]>(isJSDOM ? ['none', 'none'] : []);

    // 处理class和style，避免类型错误
    const customClass = computed(() => props.class);
    const customStyle = computed(() => props.style);

    // 内容项样式
    const itemStyle = computed(() => {
      if (props.direction === 'left' || props.direction === 'right') {
        return {
          display: 'inline-block',
          marginRight: '10px',
          verticalAlign: 'middle'
        };
      }
      return {
        display: 'block',
        marginBottom: '5px'
      };
    });

    const ssContentStyle = computed(() => {
      if ((props.direction) === 'left' || (props.direction) === 'right') {
        return {
          position: 'absolute' as const,
          top: 0,
          left: 0,
          display: 'inline-block',
          whiteSpace: 'nowrap' as const,
          verticalAlign: 'middle',
          boxSizing: 'border-box' as const
        };
      }
      return {
        position: 'absolute' as const,
        top: 0,
        left: 0,
        display: 'block',
        whiteSpace: 'normal' as const,
        width: '100%',
        boxSizing: 'border-box' as const
      };
    });

    const rows = computed(() => props.rows);
    const cols = computed(() => props.cols);
    
    const rowStyle = (rowIdx: number) => ({
      position: 'absolute' as const,
      left: 0,
      top: `${(100 / rows.value) * rowIdx}%`,
      width: '100%',
      height: `${100 / rows.value}%`,
      overflow: 'hidden',
      display: 'flex',
      alignItems: 'center'
    });
    
    const colStyle = (colIdx: number) => ({
      position: 'relative' as const,
      width: `${100 / cols.value}%`,
      height: '100%',
      display: 'inline-block',
      overflow: 'hidden',
      textAlign: 'center' as const
    });

    const updateMatrixAndTransforms = () => {
      if (isJSDOM) {
        renderMatrix.value = [props.data];
        transforms.value = ['none', 'none'];
        return;
      }
      if (instance) {
        renderMatrix.value = instance.getRenderMatrix ? instance.getRenderMatrix() : [props.data];
        transforms.value = instance.getTransforms ? instance.getTransforms() : ['none', 'none'];
      }
    };

    const start = () => { instance && instance.start(); };
    const stop = () => { instance && instance.stop(); };
    const destroy = () => { instance && instance.destroy(); };
    const updateData = () => {
      if (instance) instance.updateData();
      nextTick(() => updateMatrixAndTransforms());
    };
    const setOptions = (options: Partial<ScrollSeamlessOptions>) => { instance && instance.setOptions(options); };
    const isRunning = () => {
      const val = instance && instance.isRunning();
      return val === null ? undefined : val;
    };

    expose({ start, stop, destroy, updateData, setOptions, isRunning });

    const observeContentResize = () => {
      if (!rootRef.value) return;
      if (window.ResizeObserver) {
        resizeObserver = new ResizeObserver(() => {
          if (instance) instance.updateData();
          updateMatrixAndTransforms();
        });
        resizeObserver.observe(rootRef.value);
      }
    };
    const unobserveContentResize = () => {
      if (resizeObserver) resizeObserver.disconnect();
      resizeObserver = null;
    };

    onMounted(() => {
      if (rootRef.value) {
        const legalDirections = ['left', 'right', 'up', 'down'];
        const safeDirection = legalDirections.includes(props.direction)
          ? props.direction
          : 'left';
        const options = {
          ...props,
          direction: safeDirection,
          step: Number(props.step),
          minCountToScroll: props.minCountToScroll,
          stepWait: props.stepWait,
          delay: props.delay,
          bezier: props.bezier,
          hoverStop: props.hoverStop,
          wheelEnable: props.wheelEnable,
          singleLine: props.singleLine,
          class: props.class,
          style: props.style,
          contentClass: props.contentClass,
          itemClass: props.itemClass,
          rows: props.rows,
          cols: props.cols,
          data: props.data,
          dataDriven: true
        };
        instance = new ScrollSeamless(rootRef.value, options);
        if (props.modelValue === false) {
          instance.stop();
        }
        nextTick(() => {
          updateMatrixAndTransforms();
          observeContentResize();
        });
      }
    });

    onBeforeUnmount(() => {
      destroy();
      unobserveContentResize();
    });

    watch(() => props.modelValue, (val) => {
      if (!instance) return;
      if (val) instance.start();
      else instance.stop();
    });

    watch(() => props.data, (val) => {
      if (instance) instance.updateData();
      nextTick(() => {
        updateMatrixAndTransforms();
        unobserveContentResize();
        observeContentResize();
      });
    }, { deep: true });

    watch(() => props.step, (val) => {
      if (instance) instance.setOptions({ step: Number(val) });
    });

    return {
      rootRef,
      props,
      customClass,
      customStyle,
      ssContentStyle,
      itemStyle,
      renderMatrix,
      transforms,
      rows,
      cols,
      rowStyle,
      colStyle,
    };
  }
});
</script>

<style scoped>
.scroll-seamless-vue {
  width: 100%;
  height: 100%;
  overflow: hidden;
  position: relative;
}
.scroll-seamless-row, .scroll-seamless-col {
  display: flex;
  align-items: center;
}
.ss-content {
  position: absolute;
  transition: transform 0.05s linear;
}
.ss-item {
  display: inline-block;
  margin-right: 10px;
}
</style>

// src/react/ScrollSeamless.tsx
import React, { useRef, useEffect, useImperativeHandle, forwardRef, useState } from 'react';
import type { ForwardedRef, ReactNode, CSSProperties } from 'react';
import type { ScrollSeamlessOptions } from '../types';
import { ScrollSeamless as ScrollSeamlessCore } from '../core';

export interface ScrollSeamlessProps extends ScrollSeamlessOptions {
  children?: (item: string, index: number, rowIndex?: number, colIndex?: number) => ReactNode;
  running?: boolean;
  className?: string;
  style?: CSSProperties;
  contentClassName?: string;
  itemClassName?: string;
}

export interface ScrollSeamlessRef {
  start: () => void;
  stop: () => void;
  destroy: () => void;
  updateData: () => void;
  setOptions: (options: Partial<ScrollSeamlessOptions>) => void;
  isRunning: () => boolean | undefined;
}

const legalDirections = ['left', 'right', 'up', 'down'];

const ScrollSeamlessComponent = (
  props: ScrollSeamlessProps,
  ref: ForwardedRef<ScrollSeamlessRef>
) => {
  const rootRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<ScrollSeamlessCore | null>(null);
  const resizeObserverRef = useRef<ResizeObserver | null>(null);

  // 检测 JSDOM 测试环境
  const isJSDOM = typeof window !== 'undefined' && window.navigator && window.navigator.userAgent && window.navigator.userAgent.includes('jsdom');

  const [renderMatrix, setRenderMatrix] = useState<string[][]>(
    isJSDOM ? [props.data || []] : []
  );
  const [transforms, setTransforms] = useState<string[]>(
    isJSDOM ? ['none', 'none'] : []
  );

  useImperativeHandle(ref, () => ({
    start: () => instanceRef.current && instanceRef.current.start(),
    stop: () => instanceRef.current && instanceRef.current.stop(),
    destroy: () => instanceRef.current && instanceRef.current.destroy(),
    updateData: () => {
      instanceRef.current?.updateData();
      updateMatrixAndTransforms();
    },
    setOptions: (options) => instanceRef.current?.setOptions(options),
    isRunning: () => instanceRef.current?.isRunning(),
  }), []);

  const updateMatrixAndTransforms = () => {
    if (isJSDOM) {
      setRenderMatrix([props.data || []]);
      setTransforms(['none', 'none']);
      return;
    }
    
    if (instanceRef.current) {
      if (instanceRef.current.getRenderMatrix) {
        setRenderMatrix(instanceRef.current.getRenderMatrix());
      }
      if (instanceRef.current.getTransforms) {
        setTransforms(instanceRef.current.getTransforms());
      }
    }
  };

  // 自动监听内容尺寸变化
  const observeContentResize = () => {
    if (!rootRef.current) return;
    if (window.ResizeObserver) {
      resizeObserverRef.current = new ResizeObserver(() => {
        if (instanceRef.current) instanceRef.current.updateData();
        updateMatrixAndTransforms();
      });
      resizeObserverRef.current.observe(rootRef.current);
    }
  };
  const unobserveContentResize = () => {
    if (resizeObserverRef.current) resizeObserverRef.current.disconnect();
    resizeObserverRef.current = null;
  };

  // useEffect 仅在非 JSDOM 环境下执行实例化和监听
  useEffect(() => {
    if (isJSDOM) return;
    if (rootRef.current) {
      const safeDirection = legalDirections.includes(props.direction as string)
        ? props.direction
        : 'left';
      const options = { ...props, direction: safeDirection, dataDriven: true };
      instanceRef.current = new ScrollSeamlessCore(rootRef.current, options);
      if (props.running === false) {
        instanceRef.current.stop();
      }
      setTimeout(() => {
        updateMatrixAndTransforms();
        observeContentResize();
      }, 0);
    }
    return () => {
      instanceRef.current?.destroy();
      unobserveContentResize();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (isJSDOM) return;
    if (instanceRef.current && props.running !== undefined) {
      if (props.running) instanceRef.current.start();
      else instanceRef.current.stop();
    }
  }, [props.running]);

  useEffect(() => {
    if (isJSDOM) {
      setRenderMatrix([props.data || []]);
      setTransforms(['none', 'none']);
      return;
    }
    if (instanceRef.current) instanceRef.current.updateData();
    setTimeout(() => {
      updateMatrixAndTransforms();
      unobserveContentResize();
      observeContentResize();
    }, 0);
  }, [props.data]);

  // 功能性样式
  const baseStyle: CSSProperties = {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    position: 'relative',
  };

  const contentStyle: CSSProperties = {
    position: 'absolute',
    top: 0,
    left: 0,
    display: props.direction === 'left' || props.direction === 'right' ? 'inline-block' : 'block',
    whiteSpace: props.direction === 'left' || props.direction === 'right' ? 'nowrap' : 'normal',
    verticalAlign: props.direction === 'left' || props.direction === 'right' ? 'middle' : 'baseline',
    boxSizing: 'border-box',
    padding: props.direction === 'left' || props.direction === 'right' ? '0 5px' : '5px 0',
  };

  const itemStyle: CSSProperties = {
    display: 'inline-block',
    marginRight: '10px',
    verticalAlign: 'middle',
  };

  const rows = props.rows || 1;
  const cols = props.cols || 1;
  const rowStyle = (rowIdx: number): CSSProperties => ({
    position: 'absolute',
    left: 0,
    top: `${(100 / rows) * rowIdx}%`,
    width: '100%',
    height: `${100 / rows}%`,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
  });
  const colStyle = (colIdx: number): CSSProperties => ({
    position: 'relative',
    width: `${100 / cols}%`,
    height: '100%',
    display: 'inline-block',
    overflow: 'hidden',
    textAlign: 'center',
  });

  return (
    <div 
      ref={rootRef} 
      className={props.className}
      style={{ ...baseStyle, ...props.style }}
    >
      {props.direction === 'left' || props.direction === 'right' ? (
        renderMatrix.map((row, rowIdx) => (
          <div key={rowIdx} className="scroll-seamless-row" style={rowStyle(rowIdx)}>
            <div
              className={`ss-content ss-content-1 ${props.contentClassName || ''}`}
              style={{ ...contentStyle, transform: transforms[rowIdx*2] }}
            >
              {row.map((item, idx) =>
                props.children
                  ? props.children(item, idx, rowIdx, undefined)
                  : <span key={idx} className={props.itemClassName} style={itemStyle}>{item}</span>
              )}
            </div>
            <div
              className={`ss-content ss-content-2 ${props.contentClassName || ''}`}
              style={{ ...contentStyle, transform: transforms[rowIdx*2+1] }}
            >
              {row.map((item, idx) =>
                props.children
                  ? props.children(item, idx, rowIdx, undefined)
                  : <span key={`dup-${idx}`} className={props.itemClassName} style={itemStyle}>{item}</span>
              )}
            </div>
          </div>
        ))
      ) : (
        renderMatrix.map((col, colIdx) => (
          <div key={colIdx} className="scroll-seamless-col" style={colStyle(colIdx)}>
            <div
              className={`ss-content ss-content-1 ${props.contentClassName || ''}`}
              style={{ ...contentStyle, transform: transforms[colIdx*2] }}
            >
              {col.map((item, idx) =>
                props.children
                  ? props.children(item, idx, undefined, colIdx)
                  : <span key={idx} className={props.itemClassName} style={itemStyle}>{item}</span>
              )}
            </div>
            <div
              className={`ss-content ss-content-2 ${props.contentClassName || ''}`}
              style={{ ...contentStyle, transform: transforms[colIdx*2+1] }}
            >
              {col.map((item, idx) =>
                props.children
                  ? props.children(item, idx, undefined, colIdx)
                  : <span key={`dup-${idx}`} className={props.itemClassName} style={itemStyle}>{item}</span>
              )}
            </div>
          </div>
        ))
      )}
    </div>
  );
};

ScrollSeamlessComponent.defaultProps = {
  direction: 'left',
};

export const ScrollSeamless = forwardRef(ScrollSeamlessComponent);
